joypad_node:
  ros__parameters:
    # Topic names
    gamepad_topic: "/drive/joystick"
    joy_topic: "/joy"
    my_frame_id: "base_link"
    
    # Speed and steering parameters
    max_speed: 22.88
    steering_gain: 0.5236
    max_steering_rate: 3.2
    
    # Joystick axis mappings
    steering_axis: 0
    throttel_axis: 5
    break_axis: 2
    
    # Button mappings
    safety_button: 0
    reverse_button: 4
    pit_limit_button: 5