services: 
  robot: 
    build: 
      context: ..
      dockerfile: dockerfiles/robot.Dockerfile
      args: 
        BASE_IMAGE: "docker.io/arm64v8/ubuntu:22.04"
    image : "${ROBOT_IMAGE}:${TAG}"
    command: tail -F anything
    container_name: "${ROBOT_IMAGE}_${TAG}_container"
    network_mode: host 
    volumes:
      - ${CURRENT_DIR}/src:${CONTAINER_WS}/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    device_cgroup_rules:
      - 'c 13:* rmw' 
      - 'c 188:0 rmw'
      - 'c 166:* rmw'
      - 'c 10:229 rmw'  # /dev/uhid for Bluetooth HID emulation

