services:
  sim:
    build:
      context: ..
      dockerfile: docker/sim/sim_autodrive.Dockerfile
      # cache_from:
      #   - "${GAZEBO_SERVER_IMAGE:?}:${TAG}"
      #   - "${GAZEBO_SERVER_IMAGE:?}:main"
      # args:
      #   BASE_IMAGE: ${BASE_IMAGE_OVERRIDE-}
    # image: "${GAZEBO_SERVER_IMAGE:?}:${TAG}"
    image: autodrive_f1tenth:latest
    ports:
      - "4567:4567"
    profiles: [deploy, develop]
    # command: /bin/sh -c "echosus" #"ros2 launch autodrive_f1tenth simulator_bringup_headless.launch.py"
    # tty: true
    # command: /bin/bash
