ackermann_mux:
  ros__parameters:
    topics:
      emergancy:
        topic   : /drive/ebreak
        timeout : 0.2
        priority: 50
      joystick:
        topic   : /drive/joystick
        timeout : 0.2
        priority: 25